import express from 'express';
import { getMe, getSession, loginEmail, loginWhatsApp, logout, logoutAll, refresh, resendEmailOtp, resendWhatsAppOtp, sendEmailOtp, sendWhatsAppOtp, signupEmail, signupWhatsApp, verifyEmailOtp, verifyWhatsAppOtp } from '../controllers/authController.js';
import { otpRequestLimiter, otpVerificationLimiter, sessionLimiter } from '../middleware/securityMiddleware.js';
import { authenticate, protectCustomerRoute, requirePermission } from '../middleware/authMiddleware.js';
import { PERMISSIONS } from '../config/auth.js';
import { auditEvent } from '../services/activityLogService.js';
const router = express.Router();
const handle = (controller) => (request, response, next) => Promise.resolve(controller(request, response, next)).catch(next);
router.get('/me', protectCustomerRoute, requirePermission(PERMISSIONS.CUSTOMER_PROFILE_READ), handle(getMe));
router.get('/session', protectCustomerRoute, requirePermission(PERMISSIONS.CUSTOMER_SESSIONS_MANAGE), handle(getSession));
router.post('/email/send-otp', otpRequestLimiter, handle(sendEmailOtp));
router.post('/email/verify-otp', otpVerificationLimiter, auditEvent('auth.login', 'authentication', 'email.verify'), handle(verifyEmailOtp));
router.post('/email/signup', otpRequestLimiter, handle(signupEmail));
router.post('/email/login', otpRequestLimiter, auditEvent('auth.login.requested', 'authentication', 'email.login'), handle(loginEmail));
router.post('/email/resend', otpRequestLimiter, handle(resendEmailOtp));
router.post('/whatsapp/send-otp', otpRequestLimiter, handle(sendWhatsAppOtp));
router.post('/whatsapp/verify-otp', otpVerificationLimiter, auditEvent('auth.login', 'authentication', 'whatsapp.verify'), handle(verifyWhatsAppOtp));
router.post('/whatsapp/signup', otpRequestLimiter, handle(signupWhatsApp));
router.post('/whatsapp/login', otpRequestLimiter, auditEvent('auth.login.requested', 'authentication', 'whatsapp.login'), handle(loginWhatsApp));
router.post('/whatsapp/resend', otpRequestLimiter, handle(resendWhatsAppOtp));
router.post('/refresh', sessionLimiter, handle(refresh));
router.post('/logout', sessionLimiter, authenticate, auditEvent('auth.logout', 'authentication'), handle(logout));
router.post('/logout-all', sessionLimiter, protectCustomerRoute, requirePermission(PERMISSIONS.CUSTOMER_SESSIONS_MANAGE), auditEvent('auth.logout_all', 'authentication'), handle(logoutAll));
export default router;
