import { useState } from 'react';
import { motion } from 'framer-motion';
import { Clock, Mail, MessageCircle, PackageSearch, Phone } from 'lucide-react';
import { FiInstagram } from 'react-icons/fi';
import Seo from '../components/Seo.jsx';
import { contentService } from '../services/contentService';
import { useToast } from '../context/ToastContext';

const reveal = { hidden: { opacity: 0, y: 18 }, visible: { opacity: 1, y: 0, transition: { duration: 0.3 } } };
const message = encodeURIComponent("Hello LitePuff! I'm interested in your products and would like more information.");
const contacts = [
  { icon: MessageCircle, title: 'WhatsApp', text: 'Quick product and order help.', action: 'Start a Chat', href: `https://wa.me/918700015378?text=${message}` },
  { icon: Mail, title: 'Email', text: 'Detailed questions and feedback.', action: 'Send an Email', href: 'mailto:gnenterprises@gmail.com' },
  { icon: Phone, title: 'Phone', text: 'Speak with customer support.', action: 'Call Support', href: 'tel:+911135809124' },
  { icon: FiInstagram, title: 'Instagram', text: 'Stories, launches and community.', action: 'Follow LitePuff', href: 'https://instagram.com/litepuff_' },
];

function Field({ label, name, type = 'text', required = false }) { return <label className="relative block"><input name={name} type={type} required={required} placeholder=" " className="peer h-14 w-full rounded-[16px] border border-[#DCD4C7] bg-white px-4 pt-4 text-sm text-[#243029] outline-none transition-colors focus:border-[#1E4D3A]" /><span className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-sm text-[#68706B] transition-all peer-focus:top-3 peer-focus:text-[10px] peer-focus:font-semibold peer-focus:uppercase peer-focus:tracking-[0.1em] peer-focus:text-[#1E4D3A] peer-[:not(:placeholder-shown)]:top-3 peer-[:not(:placeholder-shown)]:text-[10px]">{label}{required ? ' *' : ''}</span></label>; }

export default function Contact() {
  const [loading, setLoading] = useState(false);
  const { showToast } = useToast();
  const submit = async (event) => { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); setLoading(true); try { await contentService.contact({ name: data.get('name'), email: data.get('email'), phone: data.get('phone'), subject: data.get('subject'), message: data.get('message') }); form.reset(); showToast('Message sent successfully.'); } catch { showToast('Unable to send your message.', 'error'); } finally { setLoading(false); } };
  return <><Seo title="Let's Talk" description="Contact LitePuff for product questions, order support and feedback." path="/contact" /><main className="bg-[#FAF8F2]">
    <header className="px-6 py-12 text-center md:py-16 lg:px-8"><motion.div className="mx-auto max-w-4xl" initial="hidden" animate="visible" variants={reveal}><p className="text-sm font-semibold uppercase tracking-[0.25em] text-[#C89B3C]">Let&apos;s Talk</p><h1 className="mt-3 font-display text-[46px] font-semibold leading-[0.98] tracking-[-0.04em] text-[#243029] md:text-[58px]">We&apos;re Always Happy<br />to Hear From You</h1><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-[#5F6762]">Questions, feedback or just saying hello—our team is here to help.</p></motion.div></header>

    <section className="px-6 pb-12 md:pb-16 lg:px-8" aria-labelledby="quick-contact-title"><div className="mx-auto max-w-7xl"><h2 id="quick-contact-title" className="sr-only">Quick contact options</h2><motion.div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4" initial="hidden" animate="visible">{contacts.map(({ icon: Icon, title, text, action, href }, index) => <motion.article key={title} className="flex flex-col rounded-[24px] border border-[#E2DBCF] bg-white p-5" variants={reveal} transition={{ delay: index * 0.04 }} whileHover={{ y: -4 }}><Icon className="h-7 w-7 text-[#C89B3C]" strokeWidth={1.5} aria-hidden="true" /><h3 className="mt-5 font-display text-[27px] font-semibold">{title}</h3><p className="mt-2 flex-1 text-sm leading-6 text-[#5F6762]">{text}</p><a href={href} target={href.startsWith('http') ? '_blank' : undefined} rel={href.startsWith('http') ? 'noreferrer' : undefined} className="mt-5 inline-flex h-11 items-center justify-center rounded-full border border-[#1E4D3A] text-sm font-semibold text-[#1E4D3A] transition-colors hover:bg-[#1E4D3A] hover:text-white">{action}</a></motion.article>)}</motion.div></div></section>

    <section className="border-y border-[#E2DBCF] bg-white px-6 py-12 md:py-16 lg:px-8" aria-labelledby="contact-form-title"><motion.div className="mx-auto grid max-w-6xl gap-9 lg:grid-cols-[40%_60%] lg:gap-12" initial="hidden" whileInView="visible" viewport={{ once: true, amount: 0.15 }}><motion.div variants={reveal}><p className="text-sm font-semibold uppercase tracking-[0.25em] text-[#C89B3C]">Write to Us</p><h2 id="contact-form-title" className="mt-3 font-display text-[42px] font-semibold leading-none tracking-[-0.04em] md:text-[48px]">Tell us what&apos;s on your mind.</h2><p className="mt-4 max-w-md text-base leading-7 text-[#5F6762]">Share a product question, order concern, partnership idea or honest feedback. We&apos;ll make sure it reaches the right person.</p><div className="mt-7 rounded-[22px] bg-[#F3EFE6] p-5"><Clock className="text-[#C89B3C]" strokeWidth={1.5} aria-hidden="true" /><p className="mt-3 text-sm font-semibold">Typical response time</p><p className="mt-1 text-sm text-[#5F6762]">Within one business day.</p></div></motion.div><motion.form onSubmit={submit} className="grid gap-4 rounded-[26px] bg-[#FAF8F2] p-5 sm:p-7" variants={reveal} aria-label="Contact LitePuff"><div className="grid gap-4 sm:grid-cols-2"><Field label="Full Name" name="name" required /><Field label="Email" name="email" type="email" required /></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Phone" name="phone" type="tel" /><label className="relative block"><select name="subject" required defaultValue="" className="h-14 w-full appearance-none rounded-[16px] border border-[#DCD4C7] bg-white px-4 pt-3 text-sm outline-none focus:border-[#1E4D3A]"><option value="" disabled>Select subject</option><option>Order Support</option><option>Product Question</option><option>Feedback</option><option>Bulk Order</option><option>Partnership</option><option>Other</option></select><span className="absolute left-4 top-2 text-[10px] font-semibold uppercase tracking-[0.1em] text-[#68706B]">Subject *</span></label></div><label className="relative block"><textarea name="message" required placeholder=" " className="peer h-40 w-full resize-y rounded-[16px] border border-[#DCD4C7] bg-white px-4 pb-3 pt-6 text-sm leading-6 outline-none focus:border-[#1E4D3A]" /><span className="pointer-events-none absolute left-4 top-5 text-sm text-[#68706B] transition-all peer-focus:top-2 peer-focus:text-[10px] peer-focus:font-semibold peer-focus:uppercase peer-focus:tracking-[0.1em] peer-[:not(:placeholder-shown)]:top-2 peer-[:not(:placeholder-shown)]:text-[10px]">Message *</span></label><button disabled={loading} className="h-13 rounded-full bg-[#1E4D3A] text-base font-semibold text-white transition-transform hover:-translate-y-0.5 disabled:opacity-60">{loading ? 'Sending…' : 'Send Message'}</button></motion.form></motion.div></section>

    <section className="px-6 py-12 md:py-16 lg:px-8" aria-labelledby="support-title"><div className="mx-auto max-w-7xl"><div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-sm font-semibold uppercase tracking-[0.25em] text-[#C89B3C]">Customer Support</p><h2 id="support-title" className="mt-2 font-display text-[42px] font-semibold leading-none">Helpful details, upfront.</h2></div><p className="max-w-md text-sm leading-6 text-[#5F6762]">Include your order number when contacting us about a purchase.</p></div><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[[Clock, 'Response Time', 'Within one business day'], [Mail, 'Business Email', 'gnenterprises@gmail.com'], [Phone, 'Phone Support', '+91 1135809124'], [PackageSearch, 'Order Support', 'Tracking, delivery and returns']].map(([Icon, title, text]) => <article key={title} className="rounded-[22px] bg-white p-5"><Icon className="text-[#C89B3C]" size={23} strokeWidth={1.5} aria-hidden="true" /><h3 className="mt-4 font-display text-[24px] font-semibold">{title}</h3><p className="mt-2 break-words text-sm leading-6 text-[#5F6762]">{text}</p></article>)}</div><div className="mt-8 grid gap-5 rounded-[26px] border border-[#E2DBCF] bg-white p-6 md:grid-cols-[1fr_auto] md:items-center"><div><h2 className="font-display text-[30px] font-semibold">Business Hours</h2><p className="mt-2 text-sm text-[#5F6762]">Monday–Saturday · 9 AM–6 PM IST &nbsp;·&nbsp; Sunday · Closed</p></div><div className="flex gap-2" aria-label="LitePuff social links">{contacts.filter((item) => ['WhatsApp', 'Email', 'Instagram'].includes(item.title)).map(({ title, href, icon: Icon }) => <a key={title} href={href} target={href.startsWith('http') ? '_blank' : undefined} rel="noreferrer" className="grid h-11 w-11 place-items-center rounded-full border border-[#1E4D3A] text-[#1E4D3A] hover:bg-[#1E4D3A] hover:text-white" aria-label={title}><Icon size={19} aria-hidden="true" /></a>)}</div></div><aside className="mt-8 rounded-[26px] bg-[#1E4D3A] p-7 text-center text-white"><h2 className="font-display text-[34px] font-semibold">Need more help?</h2><p className="mt-2 text-sm text-white/75">Browse clear answers about products, orders, shipping and returns.</p><a href="/faq" className="mt-5 inline-flex h-11 items-center rounded-full bg-[#FAF8F2] px-6 text-sm font-semibold text-[#1E4D3A]">Visit Help Center</a></aside></div></section>
  </main></>;
}
