import { useMemo, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { ChevronDown, Mail, MessageCircle, Search as FiSearch, X } from 'lucide-react';
import { Link } from 'react-router-dom';
import Seo from '../components/Seo.jsx';

const faqs = [
  { category: 'Products', question: 'How are LitePuff snacks different?', answer: 'LitePuff starts with familiar snacks and makes them more thoughtfully. Our signature makhana uses carefully selected lotus seeds, patient roasting and balanced seasoning to create a light, satisfying crunch without relying on deep frying.' },
  { category: 'Products', question: 'Are LitePuff products fried?', answer: 'Our signature makhana range is 100% roasted and never deep-fried. When new product categories launch, check the individual product page and pack because preparation methods may vary.' },
  { category: 'Ingredients', question: 'Do you use maida, gluten or preservatives?', answer: 'Our featured roasted makhana is made without maida and is presented as gluten free. Recipes vary by flavour, so the physical pack is the final source for ingredients, additives, allergens and preservatives. Customers with severe allergies should contact us before ordering.' },
  { category: 'Ingredients', question: 'Are LitePuff snacks vegetarian?', answer: 'Our current roasted makhana products are vegetarian. The green vegetarian symbol and full ingredient declaration appear on each pack so you can make an informed choice.' },
  { category: 'Orders', question: 'Can I cancel or change my order?', answer: 'Contact support immediately with your order number. A cancellation or edit is possible only before packing or dispatch begins. Once the parcel has shipped, its address, flavour and quantity cannot be changed.' },
  { category: 'Orders', question: 'How do I know my order was successful?', answer: 'A successful online payment creates an order confirmation and reference. Your account will also show the order. If money was debited but no order appears, contact us with the transaction reference before trying again.' },
  { category: 'Shipping', question: 'How long does shipping take?', answer: 'Most dispatched orders are estimated to arrive within 3 business days in serviceable locations. Remote postcodes, public holidays, weather and carrier disruptions can add time. Tracking provides the latest available estimate.' },
  { category: 'Shipping', question: 'How do I track my order?', answer: 'Open the relevant order in your LitePuff account to view its tracking reference and status. Carrier scans may take several hours after dispatch. Contact us if tracking shows no movement for an unusual period.' },
  { category: 'Returns', question: 'Can I return an opened product?', answer: 'No. Opened or partially consumed food cannot be returned for hygiene and safety reasons. If a product arrived damaged, incorrect, expired or appeared unsafe when opened, keep the item and packaging and report it within 2 days with clear photographs.' },
  { category: 'Returns', question: 'What is eligible for return?', answer: 'An unopened product with its original seal intact may be reviewed for exchange within 7 days of delivery. Approval depends on its condition and the reason for return. Personal taste preference is not a return reason for a correct, safe product.' },
  { category: 'Payments', question: 'What payment methods are accepted?', answer: 'Available secure online options—such as supported cards, UPI and net banking—are displayed by the payment gateway at checkout. LitePuff currently does not offer Cash on Delivery.' },
  { category: 'Payments', question: 'What happens if my payment fails?', answer: 'When no order is created, a temporary debit is normally reversed automatically by your bank or payment provider. If it remains after the stated reversal period, contact us with the transaction reference. Never share your OTP, PIN, CVV or password.' },
  { category: 'General', question: 'Where are LitePuff products manufactured?', answer: 'LitePuff products are prepared and packed through our Indian business operations under applicable food-safety requirements. The manufacturer, licence and batch information printed on the pack is definitive for the product you receive.' },
  { category: 'General', question: 'How can I speak to the LitePuff team?', answer: 'Email gnenterprises@gmail.com, call +91 1135809124 or message +91 8700015378 on WhatsApp. Include your order number when asking about a purchase so we can help quickly.' },
];
const categories = ['All', 'Orders', 'Shipping', 'Returns', 'Products', 'Ingredients', 'Payments', 'General'];
const whatsappMessage = encodeURIComponent("Hello LitePuff! I need help with a question.");

export default function FAQPage() {
  const [query, setQuery] = useState('');
  const [category, setCategory] = useState('All');
  const [openQuestion, setOpenQuestion] = useState(null);
  const visible = useMemo(() => { const normalized = query.trim().toLowerCase(); return faqs.filter((faq) => (category === 'All' || faq.category === category) && (!normalized || `${faq.question} ${faq.answer} ${faq.category}`.toLowerCase().includes(normalized))); }, [query, category]);
  const selectCategory = (next) => { setCategory(next); setOpenQuestion(null); };
  return <><Seo title="Help Center" description="Find clear answers about LitePuff products, orders, shipping, returns and payments." path="/faq" /><main className="bg-[#FAF8F2]">
    <header className="px-6 py-12 text-center md:py-16 lg:px-8"><p className="text-sm font-semibold uppercase tracking-[0.25em] text-[#C89B3C]">Help Center</p><h1 className="mt-3 font-display text-[48px] font-semibold leading-none tracking-[-0.04em] text-[#243029] md:text-[60px]">How Can We Help?</h1><p className="mx-auto mt-4 max-w-xl text-lg leading-8 text-[#5F6762]">Find answers to the most common questions about LitePuff.</p></header>
    <section className="px-6 pb-12 md:pb-16 lg:px-8" aria-labelledby="faq-search-title"><div className="mx-auto max-w-5xl"><h2 id="faq-search-title" className="sr-only">Search frequently asked questions</h2><label className="relative block"><FiSearch className="pointer-events-none absolute left-5 top-1/2 -translate-y-1/2 text-[#68706B]" aria-hidden="true" /><input type="search" value={query} onChange={(event) => { setQuery(event.target.value); setOpenQuestion(null); }} placeholder="Search products, orders, shipping or returns..." className="h-16 w-full rounded-[22px] border border-[#DCD4C7] bg-white pl-13 pr-14 text-base shadow-[0_8px_24px_rgba(36,48,41,0.04)] outline-none transition-shadow focus:border-[#1E4D3A] focus:shadow-[0_10px_28px_rgba(36,48,41,0.08)]" style={{ paddingLeft: '3.25rem' }} />{query ? <button type="button" onClick={() => setQuery('')} className="absolute right-4 top-1/2 grid h-9 w-9 -translate-y-1/2 place-items-center rounded-full hover:bg-[#F3EFE6]" aria-label="Clear FAQ search"><X size={18} /></button> : null}</label><div className="mt-6 flex flex-wrap justify-center gap-2.5" aria-label="FAQ categories">{categories.map((item) => <button key={item} type="button" onClick={() => selectCategory(item)} className={`h-10 rounded-full border px-4 text-sm font-semibold transition-colors ${category === item ? 'border-[#1E4D3A] bg-[#1E4D3A] text-white' : 'border-[#DCD4C7] bg-white text-[#243029] hover:border-[#1E4D3A]'}`} aria-pressed={category === item}>{item}</button>)}</div></div></section>
    <section className="border-y border-[#E2DBCF] bg-white px-6 py-12 md:py-16 lg:px-8" aria-labelledby="answers-title"><div className="mx-auto max-w-4xl"><div className="flex items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-[0.22em] text-[#C89B3C]">Popular Answers</p><h2 id="answers-title" className="mt-2 font-display text-[40px] font-semibold leading-none">{category === 'All' ? 'Everything you need to know' : category}</h2></div><p className="text-sm text-[#68706B]" aria-live="polite">{visible.length} {visible.length === 1 ? 'answer' : 'answers'}</p></div><div className="mt-7">{visible.map((faq) => { const isOpen = openQuestion === faq.question; const id = `faq-${faqs.indexOf(faq)}`; return <article key={faq.question} className="border-b border-[#E2DBCF]"><h3><button id={`${id}-button`} type="button" onClick={() => setOpenQuestion(isOpen ? null : faq.question)} className="flex w-full items-center justify-between gap-5 py-5 text-left text-base font-semibold text-[#243029] focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#C89B3C]" aria-expanded={isOpen} aria-controls={`${id}-panel`}><span><span className="mr-3 text-xs font-semibold uppercase tracking-[0.12em] text-[#C89B3C]">{faq.category}</span>{faq.question}</span><ChevronDown className={`shrink-0 transition-transform duration-300 ${isOpen ? 'rotate-180' : ''}`} size={19} aria-hidden="true" /></button></h3><AnimatePresence initial={false}>{isOpen ? <motion.div id={`${id}-panel`} role="region" aria-labelledby={`${id}-button`} initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }} transition={{ duration: 0.25 }} className="overflow-hidden"><p className="max-w-3xl pb-6 pr-10 text-sm leading-7 text-[#5F6762]">{faq.answer}</p></motion.div> : null}</AnimatePresence></article>; })}{!visible.length ? <div className="py-12 text-center"><h3 className="font-display text-3xl font-semibold">No matching answers</h3><p className="mt-2 text-sm text-[#5F6762]">Try a different word or browse all categories.</p><button type="button" onClick={() => { setQuery(''); selectCategory('All'); }} className="mt-5 h-11 rounded-full bg-[#1E4D3A] px-6 text-sm font-semibold text-white">Show All Questions</button></div> : null}</div></div></section>
    <section className="px-6 py-12 md:py-16 lg:px-8"><div className="mx-auto max-w-5xl rounded-[28px] bg-[#1E4D3A] p-7 text-center text-white md:p-10"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-[#E6C777]">Still Need Help?</p><h2 className="mt-3 font-display text-[40px] font-semibold leading-none">Didn&apos;t Find Your Answer?</h2><p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-white/75">Talk to a real person and we&apos;ll help you find the clearest next step.</p><div className="mt-6 flex flex-col justify-center gap-3 sm:flex-row"><a href={`https://wa.me/918700015378?text=${whatsappMessage}`} target="_blank" rel="noreferrer" className="inline-flex h-12 items-center justify-center gap-2 rounded-full bg-[#25D366] px-6 text-sm font-semibold text-white"><MessageCircle size={18} aria-hidden="true" />Chat on WhatsApp</a><a href="mailto:gnenterprises@gmail.com" className="inline-flex h-12 items-center justify-center gap-2 rounded-full border border-white/70 px-6 text-sm font-semibold"><Mail size={18} aria-hidden="true" />Email Us</a><Link to="/contact" className="inline-flex h-12 items-center justify-center rounded-full bg-[#FAF8F2] px-6 text-sm font-semibold text-[#1E4D3A]">Contact Page</Link></div></div></section>
  </main></>;
}
