import LegalPage from '../components/LegalPage.jsx';
const sections = [
  { id: 'scope', title: 'Scope of This Policy', content: ['This policy explains how GN Enterprises, operating the LitePuff website and store, handles personal information when you browse, create an account, place an order, contact us or subscribe to updates.'] },
  { id: 'information', title: 'Information We Collect', content: ['We collect details you choose to provide, including your name, email address, phone number, billing or delivery address, account credentials, order history, support messages and marketing preferences.', 'We also receive technical information such as device type, browser, IP address, referring page and website activity. This helps keep the store secure and understand how it performs.'] },
  { id: 'use', title: 'How We Use Your Information', content: ['We use information to create and manage accounts, validate and fulfil orders, coordinate delivery, provide tracking, respond to support requests, prevent misuse, maintain records and improve our products and website.', 'We send promotional communication only where permitted and provide a way to unsubscribe. Important service messages about orders or account security are not marketing.'] },
  { id: 'cookies', title: 'Cookies & Tracking Technologies', content: ['Essential cookies keep your cart, login and checkout working. Limited analytics may measure page performance and visitor interactions. You can restrict cookies through browser settings, although doing so may prevent account or checkout features from functioning correctly.'] },
  { id: 'payments', title: 'Payment Information', content: ['Payments are processed by an authorized payment gateway. LitePuff does not store complete card numbers, CVV values, UPI PINs or internet-banking passwords. We retain transaction references, amount, status and related order records for reconciliation, support and legal compliance.'] },
  { id: 'third-parties', title: 'Third-Party Services', content: ['We share the minimum necessary information with providers supporting payment processing, hosting, email, analytics, fraud prevention and delivery. These providers process information for defined services and are expected to apply appropriate safeguards.', 'We may disclose information where required by law, a court, regulator or lawful government request, or where reasonably necessary to protect customers, LitePuff or the public. We do not sell customer personal information.'] },
  { id: 'marketing', title: 'Marketing Communications', content: ['If you subscribe, we may send product launches, offers and snacking content by your selected channel. You can unsubscribe through the message link or contact us. Opting out of marketing does not stop order, payment, delivery or security communication.'] },
  { id: 'security', title: 'Data Security & Retention', content: ['We use reasonable administrative and technical controls to protect information. No online system is completely risk-free, so customers should use a strong password and keep login and payment credentials private.', 'We retain records only as long as reasonably needed for fulfilment, customer support, fraud prevention, accounting, tax, legal obligations and dispute handling, after which information is deleted or anonymised where practical.'] },
  { id: 'rights', title: 'Your Rights & Choices', content: ['You may ask to access, correct or delete eligible personal information, withdraw marketing consent or raise a privacy concern. Some records must be retained to meet tax, accounting, fraud-prevention or legal requirements. We may verify your identity before processing a request.'] },
  { id: 'children', title: "Children's Privacy", content: ['The LitePuff store is intended for customers who can lawfully make purchases. We do not knowingly seek personal information from children. A parent or guardian who believes a child submitted information should contact us so we can review and take appropriate action.'] },
  { id: 'updates', title: 'Policy Updates', content: ['We may revise this policy when our services, providers or legal obligations change. The updated version will appear here with a new “Last Updated” date. Material changes may also be communicated through the website or registered contact details.'] },
  { id: 'contact', title: 'Contact Information', content: ['For privacy questions or requests, email gnenterprises@gmail.com or write to GN Enterprises through the contact details published on the LitePuff website. Please describe your request clearly and include the email or phone number connected to your account.'] },
];
export default function PrivacyPolicyPage() { return <LegalPage title="Privacy Policy" path="/privacy-policy" description="How LitePuff collects, uses and protects customer information." sections={sections} />; }
