import LegalPage from '../components/LegalPage.jsx';
const sections = [
  { id: 'eligibility', title: 'Refund Eligibility', content: ['A refund may be approved when an order is cancelled before packing, is confirmed lost or undelivered, contains a verified incorrect item, or arrives damaged, expired or unsafe. Eligibility is determined after reviewing the order and supporting evidence.', 'Change of mind and personal flavour preference are not refund grounds for correctly supplied packaged food.'] },
  { id: 'damaged', title: 'Damaged or Incorrect Products', content: ['Report the issue within 2 days of delivery and keep the product, label, outer packaging and shipping materials. Clear photographs of the damage, seal, batch information and parcel help us resolve the request accurately.'] },
  { id: 'cancelled', title: 'Cancelled Orders', content: ['Contact support immediately to request cancellation. If packing or dispatch has not started, we will attempt to cancel and refund the eligible amount. Orders already dispatched cannot ordinarily be cancelled and must be assessed under the Return Policy.'] },
  { id: 'failed', title: 'Failed or Duplicate Payments', content: ['When payment fails and no order is created, banks and payment providers normally reverse the temporary debit automatically. For duplicate charges or an unreversed debit, contact us with the payment reference after the provider’s stated reversal period. Never share your PIN, password, CVV or OTP.'] },
  { id: 'method', title: 'Refund Method', content: ['Approved refunds are returned to the original online payment method used for the order. We cannot redirect a refund to another card, bank account, UPI ID or cash recipient. LitePuff does not offer Cash on Delivery.'] },
  { id: 'timeline', title: 'Refund Timeline', content: ['We initiate an approved refund promptly after verification or receipt of an approved return. The bank or payment provider may then need additional business days to post the credit. We will provide confirmation when initiation is complete.'] },
  { id: 'exceptions', title: 'Refund Exceptions', content: ['Shipping charges may be non-refundable where delivery was successfully attempted or a parcel was returned because of an incomplete address, unavailable recipient or refused delivery. Promotional discounts and coupons have no cash value and are not refunded separately.'] },
];
export default function RefundPolicyPage() { return <LegalPage title="Refund Policy" path="/refund-policy" description="LitePuff refund eligibility, methods and processing timelines." sections={sections} />; }
