import LegalPage from '../components/LegalPage.jsx';
const sections = [
  { id: 'eligibility', title: 'Return Eligibility', content: ['Because LitePuff sells packaged food, returns are limited for hygiene and food-safety reasons. An unopened product with its original seal intact may be considered for exchange when the request is submitted within 7 days of delivery.', 'Approval depends on the reason for return, pack condition, batch details and supporting information. Contact support before sending any product back.'] },
  { id: 'non-returnable', title: 'Non-Returnable Products', content: ['Opened, partially consumed, tampered, expired after delivery, improperly stored or customer-damaged products cannot be returned. A dislike of taste, spice level or texture is a personal preference and does not make an otherwise correct and safe food product returnable.', 'Clearance items, free samples and promotional gifts are not returnable unless damaged or incorrect when delivered.'] },
  { id: 'damaged', title: 'Damaged or Unsafe Products', content: ['Report crushed, leaking, unsealed, expired or apparently unsafe products within 2 days of delivery. Keep the product, outer packaging and shipping label, and send clear photographs or video showing the issue and batch information.', 'Do not consume a product if its seal is broken unexpectedly, the package is swollen or the contents appear unsafe.'] },
  { id: 'incorrect', title: 'Incorrect Orders', content: ['If you receive the wrong flavour, quantity or product, report it within 2 days. We will compare the order and packing records and arrange an appropriate replacement or other resolution after verification.'] },
  { id: 'process', title: 'Return Request Process', content: ['Email gnenterprises@gmail.com with your order number, registered contact details, reason for request and supporting images. Our team will confirm whether the request is eligible and provide collection or return instructions.', 'Products sent without approval may not be accepted or reimbursed.'] },
  { id: 'timeline', title: 'Return Timeline', content: ['Eligible sealed-product requests must be raised within 7 days of delivery. Damage, incorrect item or quality concerns must be raised within 2 days so the condition and delivery can be investigated fairly.'] },
  { id: 'responsibilities', title: 'Customer Responsibilities', content: ['Provide accurate information, retain the product and packaging during review, and pack an approved return securely. Customers are responsible for damage caused by unsuitable storage, mishandling or ignoring instructions printed on the pack.'] },
];
export default function ReturnsPolicyPage() { return <LegalPage title="Return Policy" path="/returns-policy" description="LitePuff return eligibility and process for packaged food products." sections={sections} />; }
