import LegalPage from '../components/LegalPage.jsx';
const sections = [
  { id: 'processing', title: 'Order Processing Time', content: ['We begin processing after successful payment and order validation. Most orders are prepared within 1 business day. Orders placed on public holidays or during exceptional demand may begin processing on the next working day.', 'Once packing or dispatch has started, product, quantity and address changes may no longer be possible.'] },
  { id: 'locations', title: 'Delivery Locations', content: ['LitePuff ships to serviceable addresses across India. Serviceability is checked using the postcode provided at checkout. We may be unable to deliver to restricted, remote or temporarily unavailable locations.'] },
  { id: 'timeline', title: 'Estimated Delivery Time', content: ['Most dispatched orders are estimated to arrive within 1–2 days. This is an estimate rather than a guarantee. Remote destinations, public holidays, weather, transport restrictions and carrier capacity can extend the timeline.'] },
  { id: 'charges', title: 'Shipping Charges', content: ['Standard shipping is ₹29 per order unless a different charge is clearly shown before payment. The total checkout amount includes any applicable shipping fee.'] },
  { id: 'free', title: 'Free Shipping Eligibility', content: ['Free delivery applies to eligible BUY 2 and BUY 3 combo offers when the combo remains valid through checkout. Normal product orders use the shipping charge shown in the authoritative checkout summary.'] },
  { id: 'tracking', title: 'Tracking Your Order', content: ['Tracking information appears in your LitePuff account after dispatch. Carrier scans may take several hours to begin. Use the order reference when contacting support so we can locate the shipment quickly.'] },
  { id: 'delays', title: 'Delayed Shipments', content: ['When a shipment is delayed, we work with the delivery provider to obtain an updated status. Events outside reasonable control—including severe weather, strikes, local restrictions and transport disruption—may require additional time.'] },
  { id: 'address', title: 'Incorrect or Incomplete Addresses', content: ['Customers are responsible for providing a complete address, correct postcode and reachable phone number. Contact us immediately if you notice an error. If a parcel is returned because the address was incorrect or delivery attempts failed, additional shipping charges may apply to reship it.'] },
  { id: 'lost', title: 'Lost or Missing Packages', content: ['If tracking shows delivery but the parcel cannot be found, check with household members, reception and building security before contacting us. We will request a carrier investigation. Replacement or refund decisions are made after the delivery review is completed.'] },
  { id: 'support', title: 'Shipping Support', content: ['Email gnenterprises@gmail.com or contact +91 8700015378 on WhatsApp with your order number and delivery concern. Please avoid sharing payment passwords, PINs or OTPs; LitePuff support will never request them.'] },
];
export default function ShippingPolicyPage() { return <LegalPage title="Shipping Policy" path="/shipping-policy" description="LitePuff processing, delivery, charges and tracking information." sections={sections} />; }
