import LegalPage from '../components/LegalPage.jsx';
const sections = [
  { id: 'acceptance', title: 'Acceptance of Terms', content: ['These terms govern access to the LitePuff website and purchases from GN Enterprises. By using the website, creating an account or placing an order, you agree to these terms and the policies linked from them. If you do not agree, do not use the service.'] },
  { id: 'usage', title: 'Website Usage', content: ['Use the website only for lawful, personal shopping and information. You must not interfere with security, attempt unauthorized access, submit harmful code, scrape the service at scale or use the website to mislead, impersonate or violate another person’s rights.'] },
  { id: 'products', title: 'Product Information', content: ['We aim to present product names, images, ingredients, nutrition and pack sizes accurately. Screen colours and photography can vary from the delivered pack, and packaging may be updated. The physical pack label is the definitive source for ingredients, allergens, nutrition, batch and statutory information.', 'Customers with allergies, intolerances or medical dietary needs must review the latest pack label before consumption.'] },
  { id: 'pricing', title: 'Pricing and Availability', content: ['Prices are shown in Indian rupees and include applicable product taxes unless stated otherwise. Delivery charges appear separately at checkout. Prices, offers and availability can change before an order is confirmed.', 'If an obvious pricing or technical error affects an order, we may contact you to reconfirm or cancel and refund it.'] },
  { id: 'orders', title: 'Orders and Acceptance', content: ['Submitting an order is an offer to purchase. Acceptance occurs after payment validation, stock confirmation and fulfilment review. We may limit quantities or cancel an order affected by stock error, suspected fraud, delivery restrictions or incorrect information, with an eligible refund where payment was captured.'] },
  { id: 'payments', title: 'Payments', content: ['Payments are handled through the methods displayed by the authorized payment gateway. You confirm that you are permitted to use the selected payment method. LitePuff does not request or store your UPI PIN, card PIN, banking password, CVV or OTP.'] },
  { id: 'cancellation', title: 'Cancellation, Returns and Refunds', content: ['Cancellation is possible only before packing or dispatch begins. Returns and refunds for packaged food are governed by the Return Policy and Refund Policy, including shorter reporting periods for damaged, unsafe or incorrect products.'] },
  { id: 'intellectual-property', title: 'Intellectual Property', content: ['The LitePuff name, monogram, packaging, website design, photographs, text, graphics and other brand materials belong to GN Enterprises or their respective licensors. They may not be copied, modified, republished or commercially used without written permission.'] },
  { id: 'responsibilities', title: 'User Responsibilities', content: ['Provide accurate account, delivery and contact information, protect your password, review product labels, store food as directed and inspect parcels promptly. You are responsible for activity performed through your account unless you notify us of suspected unauthorized access.'] },
  { id: 'liability', title: 'Limitation of Liability', content: ['To the extent permitted by applicable law, LitePuff is not responsible for indirect or consequential loss arising from website interruption, misuse, unsuitable storage, failure to review disclosed ingredients or events beyond reasonable control. Nothing in these terms excludes rights or remedies that cannot lawfully be excluded under Indian consumer law.'] },
  { id: 'law', title: 'Governing Law', content: ['These terms are governed by the laws of India. Courts with jurisdiction over the registered business location of GN Enterprises will have jurisdiction, subject to any mandatory consumer forum or remedy available under applicable law.'] },
  { id: 'contact', title: 'Contact Details', content: ['Questions about these terms may be sent to gnenterprises@gmail.com, by phone at +91 1135809124 or through WhatsApp at +91 8700015378. Include your order number when the question relates to a purchase.'] },
];
export default function TermsPage() { return <LegalPage title="Terms & Conditions" path="/terms" description="Terms governing the LitePuff website and customer purchases in India." sections={sections} />; }
