export const siteConfig = {
  brandName: 'LitePuff',
  siteUrl: import.meta.env.VITE_SITE_URL || (import.meta.env.PROD ? '' : 'http://localhost:5173'),
  apiBaseUrl: import.meta.env.VITE_API_BASE_URL || (import.meta.env.PROD ? '/api' : 'http://localhost:5000/api'),
  email: 'gnenterprises@gmail.com',
  phone: '+91 1135809124',
  whatsapp: '8700015378',
  address: import.meta.env.VITE_BUSINESS_ADDRESS || 'GN Enterprises',
  businessHours: '10 AM – 7 PM',
  instagram: 'https://www.instagram.com/litepuff_?utm_source=qr',
  productMrp: 249,
  productDiscountPercent: 0,
  productDiscount: 0,
  productPrice: 249,
  productWeight: '70 g',
  shippingCharge: 29,
  freeShippingQuantity: 2,
  estimatedDelivery: '3 days',
  returnWindow: '2 days'
};

export const fallbackProducts = [
  {
    id: 'peri-peri-makhana',
    metaCatalogId: 'ylq23re47d',
    name: 'Peri Peri Makhana',
    slug: 'peri-peri-makhana',
    price: 249,
    oldPrice: 249,
    shortDescription: 'Smoky, spicy roasted makhana with layered heat.',
    description: 'A bold roasted makhana flavour with smoky warmth, tangy spice, and a satisfying crunch from the first handful to the last.',
    category: 'Spicy',
    flavour: 'Peri Peri',
    images: [],
    ingredients: ['Fox nuts', 'Peri peri seasoning', 'Rock salt', 'Edible vegetable oil spray'],
    nutrition: { servingSize: '25g', calories: '95 kcal', protein: '3g', fat: '1g', carbs: '17g' },
    featured: true,
    stock: 48,
    weight: '70 gm'
  },
  {
    id: 'mint-pudina-makhana',
    metaCatalogId: 'jsvvhrmhkv',
    name: 'Mint Pudina Makhana',
    slug: 'mint-pudina-makhana',
    price: 249,
    oldPrice: 249,
    shortDescription: 'Cool, sharp and refreshing chaat-inspired crunch.',
    description: 'A fresh pudina makhana inspired by Indian street-food brightness, made light enough for everyday snacking.',
    category: 'Classic',
    flavour: 'Mint',
    images: [],
    ingredients: ['Fox nuts', 'Mint seasoning', 'Rock salt', 'Black pepper'],
    nutrition: { servingSize: '25g', calories: '90 kcal', protein: '3g', fat: '1g', carbs: '16g' },
    featured: true,
    stock: 48,
    weight: '70 gm'
  },
  {
    id: 'cheese-makhana',
    metaCatalogId: '50ta2tmgg3',
    name: 'Cheese Makhana',
    slug: 'cheese-makhana',
    price: 249,
    oldPrice: 249,
    shortDescription: 'Rich cheesy flavour without fried-chip heaviness.',
    description: 'A deeply satisfying cheese makhana that feels indulgent while staying roasted, light, and clean.',
    category: 'Creamy',
    flavour: 'Cheese',
    images: [],
    ingredients: ['Fox nuts', 'Cheese seasoning', 'Rock salt'],
    nutrition: { servingSize: '25g', calories: '98 kcal', protein: '3g', fat: '1.5g', carbs: '17g' },
    featured: true,
    stock: 48,
    weight: '70 gm'
  },
  {
    id: 'cream-onion-makhana',
    metaCatalogId: 'aj2tqtd7gb',
    name: 'Cream & Onion Makhana',
    slug: 'cream-onion-makhana',
    price: 249,
    oldPrice: 249,
    shortDescription: 'Creamy, savoury, familiar and beautifully light.',
    description: 'The classic cream and onion snack profile, slow-roasted onto premium fox nuts for a better daily snack.',
    category: 'Creamy',
    flavour: 'Cream & Onion',
    images: [],
    ingredients: ['Fox nuts', 'Cream and onion seasoning', 'Rock salt'],
    nutrition: { servingSize: '25g', calories: '96 kcal', protein: '3g', fat: '1.2g', carbs: '17g' },
    featured: true,
    stock: 48,
    weight: '70 gm'
  },
  {
    id: 'salt-pepper-makhana',
    metaCatalogId: 'uti8mwrq0k',
    name: 'Salt & Pepper Makhana',
    slug: 'salt-pepper-makhana',
    price: 249,
    oldPrice: 249,
    shortDescription: 'Simple, balanced and perfect with chai.',
    description: 'A restrained flavour with rock salt and cracked pepper that lets premium makhana speak for itself.',
    category: 'Classic',
    flavour: 'Salt & Pepper',
    images: [],
    ingredients: ['Fox nuts', 'Rock salt', 'Black pepper'],
    nutrition: { servingSize: '25g', calories: '88 kcal', protein: '3g', fat: '0.8g', carbs: '16g' },
    featured: true,
    stock: 48,
    weight: '70 gm'
  }
];

