import { OTP_DELIVERY_STATUSES, OTP_PROVIDERS, OTP_PURPOSES } from '../../config/otp.js';
import { validateEmail, validateOtp, normalizePhoneE164 } from '../../validation/domainValidation.js';
import { AppError } from '../../utils/AppError.js';
import { logger } from '../../utils/logger.js';
import { customerBusinessService } from '../business/CustomerService.js';
import { emailOtpProvider } from '../auth/EmailOTPProvider.js';
import { otpService } from '../auth/OTPService.js';
import { sessionService } from '../auth/SessionService.js';
import { whatsAppOtpProvider } from '../auth/WhatsAppOTPProvider.js';
import { identityVerificationService } from './IdentityVerificationService.js';

const truthy = (value) => value === true || String(value).toLowerCase() === 'true';
const maskEmail = (email) => { const [name, domain] = email.split('@'); return `${name.slice(0, 2)}${'*'.repeat(Math.max(1, name.length - 2))}@${domain}`; };
const maskPhone = (phone) => `${phone.slice(0, 3)}${'*'.repeat(Math.max(4, phone.length - 7))}${phone.slice(-4)}`;

export class AccountService {
  constructor({ customers = customerBusinessService, otps = otpService, sessions = sessionService, emailProvider = emailOtpProvider, whatsAppProvider = whatsAppOtpProvider, verifications = identityVerificationService } = {}) { this.customers = customers; this.otps = otps; this.sessions = sessions; this.providers = { [OTP_PROVIDERS.EMAIL]: emailProvider, [OTP_PROVIDERS.WHATSAPP]: whatsAppProvider }; this.verifications = verifications; }
  profile(customerId) { return this.customers.requireActive(customerId).then((row) => this.customers.publicIdentity(row)); }
  async updateProfile(customerId, input) { const changes = {}; for (const field of ['firstName', 'lastName']) if (input[field] !== undefined) { const value = String(input[field]).trim(); if (value.length > 80) throw new AppError(`${field} is too long.`, { status: 422, code: 'VALIDATION_ERROR', details: { field } }); changes[field] = value; } if (input.marketingConsent !== undefined) changes.marketingConsent = truthy(input.marketingConsent); if (!Object.keys(changes).length) throw new AppError('No supported profile fields were provided.', { status: 422, code: 'VALIDATION_ERROR' }); const updated = await this.customers.updateCustomer(customerId, changes); logger.info('account.profile.updated', { fields: Object.keys(changes) }); return this.customers.publicIdentity(updated); }
  normalize(channel, value) { if (channel === OTP_PROVIDERS.EMAIL) return validateEmail(value); if (channel === OTP_PROVIDERS.WHATSAPP) return normalizePhoneE164(value); throw new AppError('Recovery method is invalid.', { status: 422, code: 'RECOVERY_METHOD_INVALID' }); }
  mask(channel, value) { return channel === OTP_PROVIDERS.EMAIL ? maskEmail(value) : maskPhone(value); }
  async deliver(challenge, channel, purpose) { try { const delivery = await this.providers[channel].send({ identifier: challenge.record.Identifier, code: challenge.code, purpose }); await this.otps.recordDelivery(challenge.record.OTPID, { status: OTP_DELIVERY_STATUSES.SENT, providerMessageId: delivery.providerMessageId }); } catch (error) { await this.otps.recordDelivery(challenge.record.OTPID, { status: OTP_DELIVERY_STATUSES.FAILED }); await this.otps.invalidate(challenge.record.OTPID, 'delivery-failed'); throw error; } }
  async startChange({ customerId, channel, identifier, purpose }) { const customer = await this.customers.requireActive(customerId); const normalized = this.normalize(channel, identifier); const current = channel === OTP_PROVIDERS.EMAIL ? customer.Email : customer.Phone; if (normalized === current) throw new AppError('The new identity is unchanged.', { status: 409, code: 'IDENTITY_UNCHANGED' }); const duplicate = channel === OTP_PROVIDERS.EMAIL ? await this.customers.findByEmail(normalized) : await this.customers.findByPhone(normalized); if (duplicate) throw new AppError(`An account with this ${channel === OTP_PROVIDERS.EMAIL ? 'email' : 'phone number'} already exists.`, { status: 409, code: 'DUPLICATE_CUSTOMER' }); const challenge = await this.otps.create({ identifier: normalized, provider: channel, purpose, customerId }); await this.deliver(challenge, channel, purpose); logger.info('account.identity-change.requested', { channel, purpose }); return { otpId: challenge.record.OTPID, provider: channel, purpose, destination: this.mask(channel, normalized), expiresAt: challenge.record.ExpiresAt };
  }
  async verifyOwnedChallenge({ customerId, otpId, identifier, otp, channel, purpose }) { const normalized = this.normalize(channel, identifier); const challenge = await this.otps.get(String(otpId || '')); if (!challenge || challenge.CustomerID !== customerId) throw new AppError('OTP challenge was not found.', { status: 404, code: 'OTP_INVALID' }); await this.otps.verify({ otpId: String(otpId), identifier: normalized, provider: channel, purpose, code: validateOtp(otp) }); return { normalized, verifiedAt: new Date().toISOString() }; }
  async changeEmail(customerId, input, currentSessionId) { if (!input.otp) return this.startChange({ customerId, channel: OTP_PROVIDERS.EMAIL, identifier: input.newEmail, purpose: OTP_PURPOSES.EMAIL_CHANGE }); const verified = await this.verifyOwnedChallenge({ customerId, otpId: input.otpId, identifier: input.newEmail, otp: input.otp, channel: OTP_PROVIDERS.EMAIL, purpose: OTP_PURPOSES.EMAIL_CHANGE }); const duplicate = await this.customers.findByEmail(verified.normalized); if (duplicate && duplicate.CustomerID !== customerId) throw new AppError('An account with this email already exists.', { status: 409, code: 'DUPLICATE_CUSTOMER' }); await this.customers.updateCustomer(customerId, { email: verified.normalized, emailVerified: true, verificationDate: verified.verifiedAt, verificationMethod: 'otp', verificationSource: OTP_PROVIDERS.EMAIL }); await this.verifications.record({ customerId, channel: 'email', identifier: verified.normalized, purpose: OTP_PURPOSES.EMAIL_CHANGE, method: 'otp', source: OTP_PROVIDERS.EMAIL, verifiedAt: verified.verifiedAt }); await this.sessions.terminateOtherSessions(customerId, currentSessionId, 'email-changed'); logger.info('account.email.changed', { method: 'otp' }); return { verified: true, profile: await this.profile(customerId) }; }
  async changePhone(customerId, input, currentSessionId) { if (!input.otp) return this.startChange({ customerId, channel: OTP_PROVIDERS.WHATSAPP, identifier: input.newPhone, purpose: OTP_PURPOSES.PHONE_CHANGE }); const verified = await this.verifyOwnedChallenge({ customerId, otpId: input.otpId, identifier: input.newPhone, otp: input.otp, channel: OTP_PROVIDERS.WHATSAPP, purpose: OTP_PURPOSES.PHONE_CHANGE }); const duplicate = await this.customers.findByPhone(verified.normalized); if (duplicate && duplicate.CustomerID !== customerId) throw new AppError('An account with this phone number already exists.', { status: 409, code: 'DUPLICATE_CUSTOMER' }); await this.customers.updateCustomer(customerId, { phone: verified.normalized, phoneVerified: true, verificationDate: verified.verifiedAt, verificationMethod: 'otp', verificationSource: OTP_PROVIDERS.WHATSAPP }); await this.verifications.record({ customerId, channel: 'phone', identifier: verified.normalized, purpose: OTP_PURPOSES.PHONE_CHANGE, method: 'otp', source: OTP_PROVIDERS.WHATSAPP, verifiedAt: verified.verifiedAt }); await this.sessions.terminateOtherSessions(customerId, currentSessionId, 'phone-changed'); logger.info('account.phone.changed', { method: 'otp' }); return { verified: true, profile: await this.profile(customerId) }; }
  async recover(input, metadata = {}) { const channel = String(input.method || '').toLowerCase(); const rawIdentifier = channel === OTP_PROVIDERS.EMAIL ? input.email || input.identifier : input.phone || input.identifier; const identifier = this.normalize(channel, rawIdentifier); const customer = channel === OTP_PROVIDERS.EMAIL ? await this.customers.findByEmail(identifier) : await this.customers.findByPhone(identifier); if (!customer) throw new AppError('Customer account was not found.', { status: 404, code: 'CUSTOMER_NOT_FOUND' }); await this.customers.requireActive(customer.CustomerID);
    if (!input.otp) { const challenge = await this.otps.create({ identifier, provider: channel, purpose: OTP_PURPOSES.RECOVERY, customerId: customer.CustomerID }); await this.deliver(challenge, channel, OTP_PURPOSES.RECOVERY); logger.info('account.recovery.requested', { method: channel }); return { otpId: challenge.record.OTPID, provider: channel, purpose: OTP_PURPOSES.RECOVERY, destination: this.mask(channel, identifier), expiresAt: challenge.record.ExpiresAt }; }
    const verified = await this.verifyOwnedChallenge({ customerId: customer.CustomerID, otpId: input.otpId, identifier, otp: input.otp, channel, purpose: OTP_PURPOSES.RECOVERY }); const verificationChange = channel === OTP_PROVIDERS.EMAIL ? { emailVerified: true } : { phoneVerified: true }; await this.customers.updateCustomer(customer.CustomerID, { ...verificationChange, verificationDate: verified.verifiedAt, verificationMethod: 'otp', verificationSource: channel }); await this.customers.updateLoginTimestamp(customer.CustomerID); await this.verifications.record({ customerId: customer.CustomerID, channel, identifier, purpose: OTP_PURPOSES.RECOVERY, method: 'otp', source: channel, verifiedAt: verified.verifiedAt }); await this.sessions.terminateAllSessions(customer.CustomerID, 'account-recovery'); const current = await this.customers.requireActive(customer.CustomerID); const tokens = await this.sessions.createSession(current, { ...metadata, trusted: true }); logger.info('account.recovery.completed', { method: channel }); return { recovered: true, tokens, customer: this.customers.publicIdentity(current), session: { id: tokens.sessionId, expiresAt: tokens.expiresAt } }; }
  sessionsFor(customerId, currentSessionId) { return this.sessions.listActiveSessions(customerId, currentSessionId); }
  logoutDevice(customerId, sessionId) { return this.sessions.terminateOwnedSession(customerId, String(sessionId || ''), 'logout-device'); }
  logoutAll(customerId) { return this.sessions.terminateAllSessions(customerId, 'account-logout-all'); }
  async deleteAccount(customerId, reason = '') { await this.customers.softDelete(customerId, reason); const count = await this.sessions.terminateAllSessions(customerId, 'account-deleted'); logger.warn('account.deleted', { terminatedSessions: count }); return { deleted: true, terminatedSessions: count }; }
}
export const accountService = new AccountService();
