import ExcelJS from 'exceljs';
import { Parser } from 'json2csv';
import { conversationRepository } from '../repositories/ConversationRepository.js';
import { messageRepository } from '../repositories/MessageRepository.js';
import { campaignRepository } from '../repositories/CampaignRepository.js';
import { googleSheetsService } from './GoogleSheetsService.js';
import { customerBusinessService } from './business/CustomerService.js';
import { whatsAppMessagingService } from './WhatsAppMessagingService.js';
import { whatsAppTemplateService } from './WhatsAppTemplateService.js';
import { metaClient } from '../config/MetaClient.js';
import { whatsAppConfig } from '../config/WhatsAppConfig.js';
import { SHEET_NAMES } from '../config/sheets.js';
import { createId } from '../utils/createId.js';
import { AppError, notFound, validationError } from '../utils/AppError.js';

const pageOptions = (query) => ({ ...query, page: Number(query.page || 1), limit: Math.min(100, Number(query.limit || 25)), unread: query.unread, assigned: query.assigned, pinned: query.pinned });
const publicCustomer = (row) => row ? ({ customerId: row.CustomerID, firstName: row.FirstName, lastName: row.LastName, phone: row.Phone, email: row.Email, status: row.Status, phoneVerified: row.PhoneVerified, createdAt: row.CreatedAt }) : null;

export class DashboardService {
  constructor({ conversations = conversationRepository, messages = messageRepository, campaigns = campaignRepository, sheets = googleSheetsService, customers = customerBusinessService, messaging = whatsAppMessagingService, templates = whatsAppTemplateService, client = metaClient, config = whatsAppConfig } = {}) { Object.assign(this, { conversations, messages, campaigns, sheets, customers, messaging, templates, client, config }); }
  conversationsList(query) { return this.conversations.list(pageOptions(query)); }
  messagesList(query) { return this.messages.list(pageOptions(query)); }
  async conversationDetail(id) { const conversation = await this.conversations.findById(id); if (!conversation) throw notFound('Conversation'); const [timeline, customer, orders] = await Promise.all([this.messages.list({ conversationId: id, page: 1, limit: 100 }), conversation.CustomerID ? this.customers.findById(conversation.CustomerID) : null, this.sheets.readRows(SHEET_NAMES.ORDERS, { filter: (row) => row.CustomerID === conversation.CustomerID, sort: { field: 'CreatedAt', direction: 'desc' }, pagination: { page: 1, limit: 20 } })]); return { conversation, messages: timeline.rows, customer: publicCustomer(customer), orders: orders.rows }; }
  async customersList(query) { const result = await this.sheets.readRows(SHEET_NAMES.CUSTOMERS, { search: query.search ? { query: query.search, fields: ['CustomerID', 'FirstName', 'LastName', 'Phone', 'Email'] } : undefined, filter: (row) => (!query.status || row.Status === query.status), sort: { field: 'CreatedAt', direction: 'desc' }, pagination: pageOptions(query) }); return { ...result, rows: result.rows.map(publicCustomer) }; }
  async customerDetail(id) { const customer = await this.customers.findById(id); if (!customer) throw notFound('Customer'); const [orders, conversations] = await Promise.all([this.sheets.readRows(SHEET_NAMES.ORDERS, { filter: (row) => row.CustomerID === id, sort: { field: 'CreatedAt', direction: 'desc' } }), this.conversations.list({ customerId: id, page: 1, limit: 100 })]); return { customer: publicCustomer(customer), orders: orders.rows, conversations: conversations.rows }; }
  async search(query) { const search = String(query || '').trim(); if (!search) throw validationError('Search query is required.'); const [conversations, messages, campaigns, customers, orders] = await Promise.all([this.conversations.list({ search, page: 1, limit: 25 }), this.messages.list({ search, page: 1, limit: 25 }), this.campaigns.list({ search, page: 1, limit: 25 }), this.customersList({ search, page: 1, limit: 25 }), this.sheets.readRows(SHEET_NAMES.ORDERS, { search: { query: search, fields: ['OrderID', 'OrderNumber', 'CustomerID', 'TrackingNumber'] }, pagination: { page: 1, limit: 25 } })]); return { conversations: conversations.rows, messages: messages.rows, campaigns: campaigns.rows, customers: customers.rows, orders: orders.rows }; }
  async updateConversation(id, action, value, actorId) { if (action === 'pin') return this.conversations.pin(id, value !== false); if (action === 'assign') return this.conversations.assign(id, value || actorId); if (action === 'resolve') return this.conversations.resolve(id); if (action === 'read') { await this.messages.markConversationRead(id); return this.conversations.markRead(id); } throw validationError('Unsupported conversation action.'); }
  async send(input) { const method = input.type === 'template' ? 'sendTemplate' : ['image', 'document', 'video', 'audio', 'sticker'].includes(input.type) ? `send${input.type[0].toUpperCase()}${input.type.slice(1)}` : 'sendText'; const args = input.type === 'text' ? { to: input.to, text: input.text } : input.type === 'template' ? { to: input.to, template: input.template, variables: input.variables, name: input.name, parameters: input.parameters } : { to: input.to, id: input.mediaId, link: input.url, caption: input.caption, filename: input.filename }; const delivery = await this.messaging[method](args); return this.messages.create({ conversationId: input.conversationId, customerId: input.customerId, phone: input.to, direction: 'outbound', messageType: input.type, content: input.text || input.caption || input.variables || {}, providerMessageId: delivery.messageId, deliveryId: delivery.deliveryId, deliveryStatus: delivery.status, templateName: input.template || input.name, sentAt: delivery.sentAt }); }
  async resend(id) { const row = await this.messages.findById(id); if (!row) throw notFound('Message'); if (row.Direction !== 'outbound') throw validationError('Only outbound messages can be resent.'); const content = row.Content || ''; return this.send({ type: row.MessageType, to: row.Phone, text: row.MessageType === 'text' ? content : undefined, template: row.TemplateName || undefined, conversationId: row.ConversationID, customerId: row.CustomerID }); }
  deleteMessage(id) { return this.messages.softDelete(id); }
  async bulk(input) { const recipients = [...new Set(input.recipients || [])]; if (!recipients.length || recipients.length > 100) throw validationError('Bulk send requires between 1 and 100 unique recipients.'); const results = []; for (const to of recipients) { try { results.push({ to, success: true, message: await this.send({ ...input, to }) }); } catch (error) { results.push({ to, success: false, code: error.code || 'SEND_FAILED' }); } } return { total: recipients.length, sent: results.filter((item) => item.success).length, failed: results.filter((item) => !item.success).length, results }; }
  campaignsList(query) { return this.campaigns.list(pageOptions(query)); }
  createCampaign(input, actorId) { if (!String(input.name || '').trim()) throw validationError('Campaign name is required.'); return this.campaigns.create({ ...input, createdBy: actorId }); }
  async updateCampaign(id, input) { const current = await this.campaigns.findById(id); if (!current) throw notFound('Campaign'); return this.campaigns.update(id, input); }
  deleteCampaign(id) { return this.campaigns.remove(id); }
  changeCampaignStatus(id, status) { if (!['scheduled', 'paused', 'running', 'completed'].includes(status)) throw validationError('Campaign status is invalid.'); return this.campaigns.update(id, { Status: status, ...(status === 'paused' ? { PausedAt: new Date().toISOString() } : {}), ...(status === 'completed' ? { CompletedAt: new Date().toISOString() } : {}) }); }
  async campaignStats(id) { const campaign = await this.campaigns.findById(id); if (!campaign) throw notFound('Campaign'); const messages = await this.messages.list({ campaignId: id, page: 1, limit: 250 }); return { campaign, totalMessages: messages.pagination.total, byStatus: messages.rows.reduce((all, row) => ({ ...all, [row.DeliveryStatus]: Number(all[row.DeliveryStatus] || 0) + 1 }), {}) }; }
  async templatesList(query = {}) { return this.sheets.readRows(SHEET_NAMES.WHATSAPP_TEMPLATES, { filter: (row) => (!query.status || row.Status === query.status) && (!query.category || row.Category === query.category) && (!query.language || row.Language === query.language), search: query.search ? { query: query.search, fields: ['Name', 'Category', 'Language'] } : undefined, pagination: pageOptions(query) }); }
  async syncTemplates() { const payload = await this.client.execute(`${this.config.whatsappBusinessAccountId}/message_templates?limit=250`, { method: 'GET' }, { retries: 1 }); const now = new Date().toISOString(); for (const item of payload.data || []) { const existing = await this.sheets.readOne(SHEET_NAMES.WHATSAPP_TEMPLATES, (row) => row.Name === item.name && row.Language === item.language); const record = { TemplateID: existing?.TemplateID || createId('template'), Name: item.name, MetaTemplateID: item.id || '', Category: item.category || '', Language: item.language || '', Status: String(item.status || '').toLowerCase(), Components: JSON.stringify(item.components || []), Preview: JSON.stringify(item.components || []).slice(0, 1000), UsageCount: Number(existing?.UsageCount || 0), LastSyncedAt: now, CreatedAt: existing?.CreatedAt || now, UpdatedAt: now }; if (existing) await this.sheets.update(SHEET_NAMES.WHATSAPP_TEMPLATES, existing._row, record); else await this.sheets.append(SHEET_NAMES.WHATSAPP_TEMPLATES, record); } return { synced: (payload.data || []).length }; }
  async export(resource, format, query = {}) { const source = resource === 'campaigns' ? await this.campaignsList(query) : resource === 'conversations' ? await this.conversationsList(query) : await this.messages.list(pageOptions(query)); const rows = source.rows.map(({ _row, ...row }) => row); if (format === 'json') return { mime: 'application/json', extension: 'json', body: Buffer.from(JSON.stringify(rows, null, 2)) }; if (format === 'csv') return { mime: 'text/csv', extension: 'csv', body: Buffer.from(new Parser().parse(rows)) }; if (format !== 'xlsx') throw new AppError('Export format is not supported.', { status: 422, code: 'EXPORT_FORMAT_INVALID', expose: true }); const workbook = new ExcelJS.Workbook(); const sheet = workbook.addWorksheet(resource); if (rows.length) { sheet.columns = Object.keys(rows[0]).map((key) => ({ header: key, key })); sheet.addRows(rows); } return { mime: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', extension: 'xlsx', body: Buffer.from(await workbook.xlsx.writeBuffer()) }; }
}
export const dashboardService = new DashboardService();
