import test from 'node:test';
import assert from 'node:assert/strict';
import { AccountService } from '../services/account/AccountService.js';
import { IdentityVerificationService } from '../services/account/IdentityVerificationService.js';
import { OTPService } from '../services/auth/OTPService.js';
import { SessionService } from '../services/auth/SessionService.js';
import { JwtService } from '../services/auth/JwtService.js';
import { RefreshTokenService } from '../services/auth/RefreshTokenService.js';
import { CustomerService } from '../services/business/CustomerService.js';

class MemorySheets {
  constructor(seed = {}) { this.data = structuredClone(seed); }
  async readRows(sheet, options = {}) { let rows = [...(this.data[sheet] || [])]; if (options.filter) rows = rows.filter(options.filter); if (options.sort) rows.sort((a, b) => String(a[options.sort.field]).localeCompare(String(b[options.sort.field])) * (options.sort.direction === 'desc' ? -1 : 1)); return { rows, pagination: { total: rows.length } }; }
  async readOne(sheet, predicate) { return (this.data[sheet] || []).find(predicate) || null; }
  async append(sheet, record) { const row = { ...record, _row: (this.data[sheet]?.length || 0) + 2 }; (this.data[sheet] ||= []).push(row); return row; }
  async update(sheet, rowNumber, record) { const index = this.data[sheet].findIndex((row) => row._row === rowNumber); this.data[sheet][index] = { ...record, _row: rowNumber }; return this.data[sheet][index]; }
}
const config = { jwtSecret: 'a'.repeat(64), jwtRefreshSecret: 'b'.repeat(64), cookieSecret: 'c'.repeat(64), otpSecret: 'd'.repeat(64), accessTokenMinutes: 15, refreshTokenDays: 30, otpExpiresMinutes: 10, otpCooldownSeconds: 60, otpMaxAttempts: 3, otpMaxResends: 2, otpLockMinutes: 15, otpCleanupIntervalMinutes: 5, nodeEnv: 'test' };
const baseCustomer = { _row: 2, CustomerID: 'customer-account', FirstName: 'Lite', LastName: 'Puff', Email: 'old@example.com', Phone: '+919876543210', Role: 'customer', Status: 'active', EmailVerified: true, PhoneVerified: true, MarketingConsent: false, CreatedAt: '2025-01-01T00:00:00Z', LastLogin: '', DeletedAt: '' };
const fixture = (customer = baseCustomer) => { let now = Date.parse('2026-07-20T10:00:00Z'); const sheets = new MemorySheets({ CUSTOMERS: [customer], OTP_CHALLENGES: [], SESSIONS: [], IDENTITY_VERIFICATIONS: [] }); const customers = new CustomerService({ sheets }); const otps = new OTPService({ sheets, config, clock: () => now }); const jwt = new JwtService(config); const refreshTokens = new RefreshTokenService({ jwt, pepper: config.cookieSecret }); const sessions = new SessionService({ sheets, jwt, refreshTokens, config }); const sent = []; const provider = (channel) => ({ send: async (message) => { sent.push({ channel, ...message }); return { providerMessageId: `${channel}-${sent.length}` }; } }); const verifications = new IdentityVerificationService({ sheets, secret: config.otpSecret }); const accounts = new AccountService({ customers, otps, sessions, emailProvider: provider('email'), whatsAppProvider: provider('whatsapp'), verifications }); return { sheets, customers, otps, sessions, accounts, sent, advance: (ms) => { now += ms; } }; };

test('profile view is public-safe and update accepts only profile fields', async () => { const f = fixture(); const profile = await f.accounts.profile(baseCustomer.CustomerID); assert.equal(profile.joinedAt, baseCustomer.CreatedAt); assert.equal(profile.role, 'customer'); assert.equal(profile.PasswordHash, undefined); const updated = await f.accounts.updateProfile(baseCustomer.CustomerID, { firstName: 'Updated', marketingConsent: true, role: 'admin' }); assert.equal(updated.firstName, 'Updated'); assert.equal(updated.marketingConsent, true); assert.equal(updated.role, 'customer'); });
test('email change reuses OTP engine, records verification, and invalidates other sessions', async () => { const f = fixture(); const current = await f.sessions.createSession(baseCustomer, { userAgent: 'Chrome' }); const other = await f.sessions.createSession(baseCustomer, { userAgent: 'Firefox' }); f.otps.generateCode = () => '123456'; const started = await f.accounts.changeEmail(baseCustomer.CustomerID, { newEmail: 'new@example.com' }, current.sessionId); assert.equal(started.provider, 'email'); const result = await f.accounts.changeEmail(baseCustomer.CustomerID, { newEmail: 'new@example.com', otpId: started.otpId, otp: '123456' }, current.sessionId); assert.equal(result.profile.email, 'new@example.com'); assert.equal(result.profile.emailVerified, true); assert.equal(f.sheets.data.IDENTITY_VERIFICATIONS.length, 1); assert.equal((await f.sessions.getSession(other.sessionId)).Status, 'terminated'); assert.equal((await f.sessions.getSession(current.sessionId)).Status, 'active'); });
test('phone change normalizes E.164 and rejects duplicate phone numbers', async () => { const duplicate = { ...baseCustomer, _row: 3, CustomerID: 'other', Email: 'other@example.com', Phone: '+447700900123' }; const f = fixture(); f.sheets.data.CUSTOMERS.push(duplicate); await assert.rejects(() => f.accounts.changePhone(baseCustomer.CustomerID, { newPhone: '+44 7700 900123' }, 'session'), (error) => error.code === 'DUPLICATE_CUSTOMER'); f.otps.generateCode = () => '654321'; const started = await f.accounts.changePhone(baseCustomer.CustomerID, { newPhone: '+1 202 555 0187' }, 'session'); await f.accounts.changePhone(baseCustomer.CustomerID, { newPhone: '+12025550187', otpId: started.otpId, otp: '654321' }, 'session'); assert.equal((await f.customers.findById(baseCustomer.CustomerID)).Phone, '+12025550187'); });
test('email and WhatsApp recovery reuse OTP and replace all older sessions', async () => { for (const method of ['email', 'whatsapp']) { const f = fixture(); const old = await f.sessions.createSession(baseCustomer); f.otps.generateCode = () => '112233'; const input = method === 'email' ? { method, email: baseCustomer.Email } : { method, phone: baseCustomer.Phone }; const started = await f.accounts.recover(input); const recovered = await f.accounts.recover({ ...input, otpId: started.otpId, otp: '112233' }, { userAgent: 'Chrome', trusted: true }); assert.equal(recovered.recovered, true); assert.ok(recovered.tokens.accessToken); assert.equal((await f.sessions.getSession(old.sessionId)).Status, 'terminated'); assert.equal((await f.sessions.getSession(recovered.tokens.sessionId)).Status, 'active'); assert.equal(f.sheets.data.IDENTITY_VERIFICATIONS[0].Channel, method); } });
test('session listing, ownership checks, device logout and logout-all work', async () => { const f = fixture(); const first = await f.sessions.createSession(baseCustomer, { userAgent: 'Mozilla Chrome/120', ipAddress: '127.0.0.1' }); const second = await f.sessions.createSession(baseCustomer, { userAgent: 'Mozilla iPhone Safari/17' }); const listed = await f.accounts.sessionsFor(baseCustomer.CustomerID, first.sessionId); assert.equal(listed.length, 2); assert.equal(listed.find((row) => row.id === first.sessionId).isCurrent, true); assert.equal(listed.find((row) => row.id === second.sessionId).device, 'Mobile'); await f.accounts.logoutDevice(baseCustomer.CustomerID, second.sessionId); assert.equal((await f.sessions.getSession(second.sessionId)).Status, 'terminated'); await assert.rejects(() => f.accounts.logoutDevice('other-customer', first.sessionId), (error) => error.code === 'SESSION_NOT_FOUND'); assert.equal(await f.accounts.logoutAll(baseCustomer.CustomerID), 1); });
test('soft deletion preserves the customer, records reason, revokes sessions and blocks login', async () => { const f = fixture(); await f.sessions.createSession(baseCustomer); const result = await f.accounts.deleteAccount(baseCustomer.CustomerID, 'customer request'); assert.equal(result.deleted, true); const row = await f.customers.findById(baseCustomer.CustomerID); assert.equal(row.Status, 'deleted'); assert.ok(row.DeletedAt); assert.equal(row.DeletedReason, 'customer request'); await assert.rejects(() => f.customers.requireActive(baseCustomer.CustomerID), (error) => error.code === 'CUSTOMER_DELETED'); assert.equal((await f.accounts.sessionsFor(baseCustomer.CustomerID, '')).length, 0); });
test('blocked customer recovery is rejected before an OTP is created', async () => { const f = fixture({ ...baseCustomer, Status: 'blocked' }); await assert.rejects(() => f.accounts.recover({ method: 'email', email: baseCustomer.Email }), (error) => error.code === 'CUSTOMER_BLOCKED'); assert.equal(f.sheets.data.OTP_CHALLENGES.length, 0); });
