import test from 'node:test';
import assert from 'node:assert/strict';
import { AUTH_ROLES, PERMISSIONS } from '../config/auth.js';
import { AuthorizationService } from '../services/security/AuthorizationService.js';
import { AuditLogService } from '../services/security/AuditLogService.js';
import { AccountSecurityService } from '../services/security/AccountSecurityService.js';
import { createAuthorizationMiddleware } from '../middleware/authMiddleware.js';
import { csrfArchitectureGuard, securityStack } from '../middleware/securityMiddleware.js';
import { CustomerService } from '../services/business/CustomerService.js';

class MemorySheets { constructor(seed = {}) { this.data = structuredClone(seed); } async readRows(sheet, options = {}) { let rows = [...(this.data[sheet] || [])]; if (options.filter) rows = rows.filter(options.filter); return { rows }; } async readOne(sheet, predicate) { return (this.data[sheet] || []).find(predicate) || null; } async append(sheet, record) { const row = { ...record, _row: (this.data[sheet]?.length || 0) + 2 }; (this.data[sheet] ||= []).push(row); return row; } async update(sheet, rowNumber, record) { const index = this.data[sheet].findIndex((row) => row._row === rowNumber); this.data[sheet][index] = { ...record, _row: rowNumber }; return this.data[sheet][index]; } }
const invoke = (middleware, request) => new Promise((resolve, reject) => middleware(request, {}, (error) => error ? reject(error) : resolve(request)));

test('central role matrix validates all roles and expected permissions', () => { const service = new AuthorizationService(); assert.equal(service.hasPermission(AUTH_ROLES.CUSTOMER, PERMISSIONS.CUSTOMER_PROFILE_READ), true); assert.equal(service.hasPermission(AUTH_ROLES.CUSTOMER, PERMISSIONS.ADMIN_PRODUCTS_READ), false); assert.equal(service.hasPermission(AUTH_ROLES.SUPPORT, PERMISSIONS.ADMIN_ORDERS_READ), true); assert.equal(service.hasPermission(AUTH_ROLES.SUPPORT, PERMISSIONS.ADMIN_PRODUCTS_DELETE), false); assert.equal(service.hasPermission(AUTH_ROLES.MANAGER, PERMISSIONS.ADMIN_ANALYTICS_VIEW), true); assert.equal(service.hasPermission(AUTH_ROLES.ADMIN, PERMISSIONS.ADMIN_PRODUCTS_DELETE), true); assert.equal(service.hasPermission(AUTH_ROLES.SUPER_ADMIN, PERMISSIONS.ADMIN_ROLES_MANAGE), true); assert.equal(service.normalizeRole('staff'), AUTH_ROLES.SUPPORT); assert.throws(() => service.validateRole('owner'), (error) => error.code === 'INVALID_ROLE'); assert.throws(() => service.validatePermission('made.up'), (error) => error.code === 'INVALID_PERMISSION'); });
test('authorization decisions distinguish unauthorized and forbidden access', () => { const service = new AuthorizationService(); assert.throws(() => service.requirePermission({ id: '', role: 'guest' }, PERMISSIONS.CUSTOMER_PROFILE_READ), (error) => error.status === 401); assert.throws(() => service.requirePermission({ id: 'customer', role: 'customer' }, PERMISSIONS.ADMIN_PRODUCTS_READ), (error) => error.code === 'MISSING_PERMISSION'); assert.equal(service.requirePermission({ id: 'manager', role: 'manager' }, PERMISSIONS.ADMIN_ANALYTICS_VIEW), true); });
test('ownership allows owners and privileged bypass while denying other customers', () => { const service = new AuthorizationService(); assert.equal(service.requireOwnership({ id: 'c1', role: 'customer' }, 'c1'), true); assert.throws(() => service.requireOwnership({ id: 'c2', role: 'customer' }, 'c1'), (error) => error.code === 'OWNERSHIP_REQUIRED'); assert.equal(service.requireOwnership({ id: 'admin', role: 'admin' }, 'c1', { bypassPermission: PERMISSIONS.ADMIN_ORDERS_MANAGE }), true); });
test('authorization middleware audits grants and denials and enforces resource ownership', async () => { const events = []; const audit = { recordSafe: (entry) => events.push(entry) }; const ownership = { owner: async () => ({ ownerId: 'c1', row: { OrderID: 'o1', CustomerID: 'c1' } }) }; const middleware = createAuthorizationMiddleware({ authorization: new AuthorizationService(), audit, ownership }); const granted = { auth: { customerId: 'c1', role: 'customer' }, baseUrl: '/api/account', method: 'GET', params: { id: 'o1' } }; await invoke(middleware.requirePermission(PERMISSIONS.CUSTOMER_PROFILE_READ), granted); await invoke(middleware.requireOwnership('order'), granted); assert.equal(granted.ownedResource.OrderID, 'o1'); await assert.rejects(() => invoke(middleware.requirePermission(PERMISSIONS.ADMIN_PRODUCTS_DELETE), granted), (error) => error.code === 'MISSING_PERMISSION'); assert.ok(events.some((event) => event.decision === 'granted')); assert.ok(events.some((event) => event.decision === 'denied')); });
test('audit records redact sensitive metadata and hash IP addresses', async () => { const sheets = new MemorySheets({ AUTH_AUDIT: [] }); const audit = new AuditLogService({ sheets, secret: 'audit-secret' }); await audit.record({ request: { ip: '127.0.0.1', id: 'request-1', get: () => 'Browser' }, actor: { id: 'c1', role: 'customer', type: 'customer' }, event: 'profile.updated', decision: 'completed', metadata: { field: 'firstName', token: 'must-not-store', email: 'private@example.com' } }); const row = sheets.data.AUTH_AUDIT[0]; assert.notEqual(row.IPHash, '127.0.0.1'); assert.doesNotMatch(row.Metadata, /must-not-store|private@example.com/); assert.equal(row.ActorRole, 'customer'); });
test('temporary lock, suspension and permanent ban revoke sessions and block accounts', async () => { const customer = { _row: 2, CustomerID: 'c1', Email: 'c@example.com', Phone: '+919876543210', Role: 'customer', Status: 'active', DeletedAt: '' }; const sheets = new MemorySheets({ CUSTOMERS: [customer] }); const customers = new CustomerService({ sheets }); const terminations = []; const security = new AccountSecurityService({ customers, sessions: { terminateAllSessions: async (id, reason) => terminations.push({ id, reason }) } }); await security.temporaryLock('c1', Date.now() + 60_000); await assert.rejects(() => customers.requireActive('c1'), (error) => error.code === 'ACCOUNT_TEMPORARILY_LOCKED'); await security.clearTemporaryLock('c1'); await security.suspend('c1'); await assert.rejects(() => customers.requireActive('c1'), (error) => error.code === 'CUSTOMER_SUSPENDED'); await customers.updateCustomer('c1', { status: 'active' }); await security.ban('c1'); await assert.rejects(() => customers.requireActive('c1'), (error) => error.code === 'CUSTOMER_BLOCKED'); assert.equal(terminations.length, 3); });
test('security middleware rejects operator-key injection and cross-origin cookie mutations', async () => { const sanitizer = securityStack.at(-1); await assert.rejects(() => invoke(sanitizer, { body: { '$where': 'bad' }, query: {} }), (error) => error.code === 'UNSAFE_INPUT'); const oldFrontend = process.env.FRONTEND_URL; process.env.FRONTEND_URL = 'https://litepuff.example'; await assert.rejects(() => invoke(csrfArchitectureGuard, { method: 'POST', signedCookies: { lp_access: 'signed' }, get: () => 'https://evil.example' }), (error) => error.code === 'CSRF_ORIGIN_REJECTED'); process.env.FRONTEND_URL = oldFrontend; });
