import test from 'node:test';
import assert from 'node:assert/strict';
import { normalizePhoneE164 } from '../validation/domainValidation.js';
import { WhatsAppTemplateBuilder } from '../services/auth/WhatsAppTemplateBuilder.js';
import { MetaWhatsAppClient } from '../services/auth/MetaWhatsAppClient.js';
import { WhatsAppOTPProvider } from '../services/auth/WhatsAppOTPProvider.js';
import { AuthService } from '../services/auth/AuthService.js';
import { OTPService } from '../services/auth/OTPService.js';
import { CustomerService } from '../services/business/CustomerService.js';
import { JwtService } from '../services/auth/JwtService.js';
import { RefreshTokenService } from '../services/auth/RefreshTokenService.js';
import { SessionService } from '../services/auth/SessionService.js';

class MemorySheets {
  constructor(seed = {}) { this.data = structuredClone(seed); }
  async readRows(sheet, options = {}) { let rows = [...(this.data[sheet] || [])]; if (options.filter) rows = rows.filter(options.filter); if (options.sort) rows.sort((a, b) => String(a[options.sort.field]).localeCompare(String(b[options.sort.field])) * (options.sort.direction === 'desc' ? -1 : 1)); return { rows, pagination: { total: rows.length } }; }
  async readOne(sheet, predicate) { return (this.data[sheet] || []).find(predicate) || null; }
  async append(sheet, record) { const row = { ...record, _row: (this.data[sheet]?.length || 0) + 2 }; (this.data[sheet] ||= []).push(row); return row; }
  async update(sheet, rowNumber, record) { const index = this.data[sheet].findIndex((row) => row._row === rowNumber); this.data[sheet][index] = { ...record, _row: rowNumber }; return this.data[sheet][index]; }
}
const config = { jwtSecret: 'a'.repeat(64), jwtRefreshSecret: 'b'.repeat(64), cookieSecret: 'c'.repeat(64), otpSecret: 'd'.repeat(64), accessTokenMinutes: 15, refreshTokenDays: 30, otpExpiresMinutes: 10, otpCooldownSeconds: 60, otpMaxAttempts: 3, otpMaxResends: 2, otpLockMinutes: 15, otpCleanupIntervalMinutes: 5, nodeEnv: 'test', whatsappAccessToken: 'meta-secret', whatsappPhoneNumberId: 'phone-id', whatsappBusinessAccountId: 'waba-id', whatsappTemplateLanguage: 'en_US', whatsappAuthTemplate: 'litepuff_authentication', whatsappOrderTemplate: 'litepuff_order_confirmation', whatsappShippingTemplate: 'litepuff_shipping_update', whatsappMarketingTemplate: 'litepuff_marketing', whatsappAuthCodeButton: true, whatsappTimeoutMs: 1000, whatsappMaxRetries: 2, metaApiVersion: 'v23.0' };

const fixture = (seedCustomers = []) => { let now = Date.parse('2026-07-20T10:00:00Z'); const sheets = new MemorySheets({ CUSTOMERS: seedCustomers, OTP_CHALLENGES: [], SESSIONS: [] }); const otps = new OTPService({ sheets, config, clock: () => now }); const customers = new CustomerService({ sheets }); const jwt = new JwtService(config); const refreshTokens = new RefreshTokenService({ jwt, pepper: config.cookieSecret }); const sessions = new SessionService({ sheets, jwt, refreshTokens, config }); const deliveries = []; const whatsAppProvider = { send: async (message) => { deliveries.push(message); return { providerMessageId: `wamid.${deliveries.length}`, status: 'accepted' }; } }; const emailProvider = { send: async () => ({ providerMessageId: 'mail' }) }; const auth = new AuthService({ customers, otps, whatsAppProvider, emailProvider, sessions, jwt }); return { sheets, otps, customers, sessions, auth, deliveries, advance: (ms) => { now += ms; } }; };

test('phone validation normalizes valid E.164 input and rejects missing/invalid country codes', () => { assert.equal(normalizePhoneE164('+91 98765-43210'), '+919876543210'); assert.equal(normalizePhoneE164('00442079460958'), '+442079460958'); assert.throws(() => normalizePhoneE164('9876543210'), (error) => error.code === 'VALIDATION_ERROR'); assert.throws(() => normalizePhoneE164('+0123'), (error) => error.code === 'VALIDATION_ERROR'); });
test('authentication template builder selects configured LitePuff template and code button', () => { const template = new WhatsAppTemplateBuilder(config).build('authentication', { code: '123456', expiresMinutes: 10 }); assert.equal(template.name, config.whatsappAuthTemplate); assert.equal(template.language.code, 'en_US'); assert.equal(template.components[0].parameters[0].text, '123456'); assert.equal(template.components[1].type, 'button'); });
test('Meta client sends the expected Cloud API payload and reads message IDs', async () => { let captured; const client = new MetaWhatsAppClient({ config, request: async (url, options) => { captured = { url, options }; return { ok: true, status: 200, json: async () => ({ messages: [{ id: 'wamid.accepted', message_status: 'accepted' }] }) }; } }); const template = new WhatsAppTemplateBuilder(config).build('authentication', { code: '123456', expiresMinutes: 10 }); const result = await client.sendTemplate({ to: '+919876543210', template }); assert.match(captured.url, /v23\.0\/phone-id\/messages$/); const body = JSON.parse(captured.options.body); assert.equal(body.to, '919876543210'); assert.equal(body.type, 'template'); assert.equal(result.messageId, 'wamid.accepted'); assert.doesNotMatch(JSON.stringify(body), /meta-secret/); });
test('Meta client maps access, template, phone and rate-limit failures', async () => { const response = (code, status = 400) => async () => ({ ok: false, status, json: async () => ({ error: { code, message: 'sensitive provider text' } }) }); for (const [metaCode, expected] of [[190, 'WHATSAPP_ACCESS_TOKEN_INVALID'], [132001, 'WHATSAPP_TEMPLATE_MISSING'], [131026, 'WHATSAPP_PHONE_UNREACHABLE'], [130429, 'WHATSAPP_RATE_LIMITED']]) { const client = new MetaWhatsAppClient({ config, request: response(metaCode, metaCode === 130429 ? 429 : 400) }); await assert.rejects(() => client.sendTemplate({ to: '+919876543210', template: { name: 'x', language: { code: 'en' }, components: [] } }), (error) => error.code === expected); } });
test('WhatsApp OTP provider delegates delivery to the centralized messaging service', async () => { const calls = []; const provider = new WhatsAppOTPProvider({ otpExpiresMinutes: 10, messaging: { sendTemplate: async (input) => { calls.push(input); return { messageId: 'wamid.ok', status: 'sent' }; } } }); const result = await provider.send({ identifier: '+919876543210', code: '123456', purpose: 'login' }); assert.equal(result.providerMessageId, 'wamid.ok'); assert.equal(calls[0].template, 'authentication'); assert.equal(calls[0].variables.expiresMinutes, 10); assert.equal(calls[0].variables.code, '123456'); });
test('WhatsApp signup and login reuse OTPService and create secure session tokens', async () => { const f = fixture(); f.otps.generateCode = () => f.deliveries.length ? '654321' : '123456'; const signup = await f.auth.signupWhatsApp({ phone: '+91 98765 43210' }); assert.equal(signup.provider, 'whatsapp'); assert.match(signup.destination, /3210$/); const created = await f.auth.verifyWhatsAppOtp({ otpId: signup.otpId, phone: '+919876543210', otp: '123456', purpose: 'signup', firstName: 'New' }); assert.equal(created.customer.phone, '+919876543210'); assert.equal(created.customer.phoneVerified, true); assert.ok(created.tokens.accessToken); assert.equal(f.sheets.data.SESSIONS.length, 1); f.advance(61_000); const login = await f.auth.loginWhatsApp({ phone: '+919876543210' }); await f.auth.verifyWhatsAppOtp({ otpId: login.otpId, phone: '+919876543210', otp: '654321', purpose: 'login' }); assert.equal(f.sheets.data.SESSIONS.length, 2); assert.ok(f.sheets.data.CUSTOMERS[0].LastLogin); await assert.rejects(() => f.auth.signupWhatsApp({ phone: '+919876543210' }), (error) => error.code === 'DUPLICATE_CUSTOMER'); });
test('WhatsApp login rejects blocked and soft-deleted customers before creating OTPs', async () => { for (const customer of [{ _row: 2, CustomerID: 'blocked', Phone: '+919876543210', Status: 'blocked', Role: 'customer', DeletedAt: '' }, { _row: 2, CustomerID: 'deleted', Phone: '+919876543210', Status: 'inactive', Role: 'customer', DeletedAt: '2026-01-01T00:00:00Z' }]) { const f = fixture([customer]); await assert.rejects(() => f.auth.loginWhatsApp({ phone: customer.Phone }), (error) => ['CUSTOMER_BLOCKED', 'CUSTOMER_DELETED'].includes(error.code)); assert.equal(f.sheets.data.OTP_CHALLENGES.length, 0); } });
