import test from 'node:test';
import assert from 'node:assert/strict';
import { ConversationRepository } from '../repositories/ConversationRepository.js';
import { MessageRepository } from '../repositories/MessageRepository.js';
import { CampaignRepository } from '../repositories/CampaignRepository.js';
import { AnalyticsRepository } from '../repositories/AnalyticsRepository.js';
import { AnalyticsService } from '../services/AnalyticsService.js';
import { DashboardService } from '../services/DashboardService.js';
import { SHEET_NAMES } from '../config/sheets.js';

class MemorySheets {
  constructor() { this.data = Object.fromEntries(Object.values(SHEET_NAMES).map((name) => [name, []])); }
  async readOne(sheet, predicate) { return this.data[sheet].find(predicate) || null; }
  async readRows(sheet, options = {}) { let rows = [...this.data[sheet]]; if (options.filter) rows = rows.filter(options.filter); if (options.search?.query) { const q = options.search.query.toLowerCase(); rows = rows.filter((row) => options.search.fields.some((field) => String(row[field] || '').toLowerCase().includes(q))); } if (options.sort) rows.sort((a, b) => String(a[options.sort.field] || '').localeCompare(String(b[options.sort.field] || '')) * (options.sort.direction === 'desc' ? -1 : 1)); const total = rows.length; const page = Number(options.pagination?.page || 1); const limit = Number(options.pagination?.limit || total || 1); if (options.pagination) rows = rows.slice((page - 1) * limit, page * limit); return { rows, pagination: { page, limit, total, pages: Math.max(1, Math.ceil(total / limit)) } }; }
  async append(sheet, row) { const stored = { ...row, _row: this.data[sheet].length + 2 }; this.data[sheet].push(stored); return stored; }
  async update(sheet, rowNumber, row) { const index = this.data[sheet].findIndex((item) => item._row === rowNumber); this.data[sheet][index] = { ...row, _row: rowNumber }; return this.data[sheet][index]; }
  async batchRead(requests) { return Object.fromEntries(await Promise.all(requests.map(async ({ sheet, options }) => [sheet, await this.readRows(sheet, options)]))); }
}

function fixture() { const sheets = new MemorySheets(); const conversations = new ConversationRepository({ sheets }); const messages = new MessageRepository({ sheets }); const campaigns = new CampaignRepository({ sheets }); const repository = new AnalyticsRepository({ sheets }); const messaging = { sendText: async () => ({ messageId: 'wamid.sent', deliveryId: 'delivery-1', status: 'sent', sentAt: new Date().toISOString() }) }; const customers = { findById: async (id) => sheets.readOne(SHEET_NAMES.CUSTOMERS, (row) => row.CustomerID === id) }; const dashboard = new DashboardService({ conversations, messages, campaigns, sheets, customers, messaging, templates: {}, client: {}, config: {} }); return { sheets, conversations, messages, campaigns, dashboard, analytics: new AnalyticsService({ repository }) }; }

test('dashboard lists, searches, filters, pins and assigns conversations', async () => { const f = fixture(); const conversation = await f.conversations.create({ phone: '+919876543210', customerId: 'customer-1' }); await f.conversations.update(conversation.ConversationID, { UnreadCount: 2 }); assert.equal((await f.dashboard.conversationsList({ search: '9876', unread: 'true' })).pagination.total, 1); assert.equal((await f.dashboard.updateConversation(conversation.ConversationID, 'pin', true, 'admin-1')).IsPinned, 'true'); assert.equal((await f.dashboard.updateConversation(conversation.ConversationID, 'assign', '', 'admin-1')).AssignedTo, 'admin-1'); });
test('message management sends, stores, resends and soft deletes', async () => { const f = fixture(); const sent = await f.dashboard.send({ type: 'text', to: '+919876543210', text: 'Hello' }); assert.equal(sent.DeliveryStatus, 'sent'); const resent = await f.dashboard.resend(sent.MessageID); assert.equal(resent.Phone, '+919876543210'); await f.dashboard.deleteMessage(sent.MessageID); assert.equal(await f.messages.findById(sent.MessageID), null); });
test('bulk sending is bounded and reports partial outcomes', async () => { const f = fixture(); const result = await f.dashboard.bulk({ type: 'text', text: 'Update', recipients: ['+919876543210', '+919876543211'] }); assert.equal(result.sent, 2); await assert.rejects(() => f.dashboard.bulk({ type: 'text', recipients: [] }), (error) => error.code === 'VALIDATION_ERROR'); });
test('campaign lifecycle supports create, schedule, pause, resume and soft delete', async () => { const f = fixture(); const campaign = await f.dashboard.createCampaign({ name: 'Launch', templateName: 'welcome' }, 'admin-1'); assert.equal(campaign.Status, 'draft'); assert.equal((await f.dashboard.changeCampaignStatus(campaign.CampaignID, 'scheduled')).Status, 'scheduled'); assert.equal((await f.dashboard.changeCampaignStatus(campaign.CampaignID, 'paused')).Status, 'paused'); assert.equal((await f.dashboard.changeCampaignStatus(campaign.CampaignID, 'running')).Status, 'running'); assert.equal((await f.dashboard.deleteCampaign(campaign.CampaignID)).Status, 'deleted'); });
test('analytics calculates delivery, conversation, campaign and customer metrics', async () => { const f = fixture(); await f.messages.create({ phone: '+919876543210', deliveryStatus: 'delivered', sentAt: new Date().toISOString() }); await f.conversations.create({ phone: '+919876543210' }); await f.campaigns.create({ name: 'Launch' }); await f.sheets.append(SHEET_NAMES.CUSTOMERS, { CustomerID: 'c1', Status: 'active', PhoneVerified: 'true', CreatedAt: new Date().toISOString() }); const result = await f.analytics.get(); assert.equal(result.totalMessages, 1); assert.equal(result.delivered, 1); assert.equal(result.activeConversations, 1); assert.equal(result.customerGrowth.totalCustomers, 1); });
test('CSV, Excel and JSON exports contain dashboard data', async () => { const f = fixture(); await f.conversations.create({ phone: '+919876543210' }); for (const format of ['csv', 'xlsx', 'json']) { const file = await f.dashboard.export('conversations', format); assert.ok(file.body.length > 0); assert.equal(file.extension, format); } });
